version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "51883:1883" # MQTT default port
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "3",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "55672:5672" # AMQP protocol port
      - "55673:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  delta-helper:
    image: europe-west3-docker.pkg.dev/nano-green-1/public/backend-home-assignment-helper:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      MQTT_URL: mqtt://mosquitto:1883
      MQTT_USERNAME: admin
      MQTT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_healthy

volumes:
  mosquitto_data:
  mosquitto_log:
  postgres_data:
  rabbitmq_data:
